// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMCkOxXC__rUuS3rBJmVQwglXqXyRXeQ',
    appId: '1:1024789455456:web:e0ee0572c95e2123459905',
    messagingSenderId: '1024789455456',
    projectId: 'loginregsys',
    authDomain: 'loginregsys.firebaseapp.com',
    storageBucket: 'loginregsys.firebasestorage.app',
    measurementId: 'G-FZP25V8D98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvUoJm3Cc6B5yFEc0uPTs33-oI9d2lg0',
    appId: '1:1024789455456:android:e201116a70b32378459905',
    messagingSenderId: '1024789455456',
    projectId: 'loginregsys',
    storageBucket: 'loginregsys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1ZZK6EbR1G0W3EshO9vKiVbG5-K7yTo',
    appId: '1:1024789455456:ios:2f117d6de006b701459905',
    messagingSenderId: '1024789455456',
    projectId: 'loginregsys',
    storageBucket: 'loginregsys.firebasestorage.app',
    iosBundleId: 'loginregsys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1ZZK6EbR1G0W3EshO9vKiVbG5-K7yTo',
    appId: '1:1024789455456:ios:2f117d6de006b701459905',
    messagingSenderId: '1024789455456',
    projectId: 'loginregsys',
    storageBucket: 'loginregsys.firebasestorage.app',
    iosBundleId: 'loginregsys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmMCkOxXC__rUuS3rBJmVQwglXqXyRXeQ',
    appId: '1:1024789455456:web:b8dcff6f50d9cc5c459905',
    messagingSenderId: '1024789455456',
    projectId: 'loginregsys',
    authDomain: 'loginregsys.firebaseapp.com',
    storageBucket: 'loginregsys.firebasestorage.app',
    measurementId: 'G-N6M0NBDET7',
  );
}
